USE [SICEX_INSPECCION]
GO

/****** Object:  Table [dbo].[DISTRITO_JUDICIAL]    Script Date: 08/06/2024 10:01:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DISTRITO_JUDICIAL](
	[id_distrito_judicial] [int] NOT NULL,
	[nombre_distrito] [char](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_distrito_judicial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[ESPECIALIDAD](
	[id_especialidad] [int] NOT NULL,
	[nombre_especialidad] [char](50) NOT NULL,
	[id_instancia] [int] NOT NULL,
	[id_especialidad_cje] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_especialidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ESPECIALIDAD]  WITH CHECK ADD  CONSTRAINT [FK_ESPECIALIDAD_INSTANCIA] FOREIGN KEY([id_instancia])
REFERENCES [dbo].[INSTANCIA] ([id_instancia])
GO

ALTER TABLE [dbo].[ESPECIALIDAD] CHECK CONSTRAINT [FK_ESPECIALIDAD_INSTANCIA]
GO

CREATE TABLE [dbo].[EXPEDIENTE_CABECERA](
	[id_distrito_judicial] [int] NOT NULL,
	[id_instancia] [int] NOT NULL,
	[id_especialidad] [int] NOT NULL,
	[año] [int] NOT NULL,
	[correlativo] [int] NOT NULL,
	[id_area_sige] [int] NULL,
	[id_secuencia] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_id_secuencia] PRIMARY KEY CLUSTERED 
(
	[id_secuencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXPEDIENTE_CABECERA]  WITH CHECK ADD  CONSTRAINT [FK_EXPEDIENTE_CABECERA_DISTRITO_JUDICIAL] FOREIGN KEY([id_distrito_judicial])
REFERENCES [dbo].[DISTRITO_JUDICIAL] ([id_distrito_judicial])
GO

ALTER TABLE [dbo].[EXPEDIENTE_CABECERA] CHECK CONSTRAINT [FK_EXPEDIENTE_CABECERA_DISTRITO_JUDICIAL]
GO

ALTER TABLE [dbo].[EXPEDIENTE_CABECERA]  WITH CHECK ADD  CONSTRAINT [FK_EXPEDIENTE_CABECERA_INSTANCIA1] FOREIGN KEY([id_instancia])
REFERENCES [dbo].[INSTANCIA] ([id_instancia])
GO

ALTER TABLE [dbo].[EXPEDIENTE_CABECERA] CHECK CONSTRAINT [FK_EXPEDIENTE_CABECERA_INSTANCIA1]
GO
CREATE TABLE [dbo].[EXPEDIENTE_DETALLE](
	[numero_expediente] [char](27) NOT NULL,
	[organo_jurisdiccional] [varchar](100) NOT NULL,
	[juez] [char](100) NULL,
	[fecha_inicio] [date] NULL,
	[observacion] [char](200) NULL,
	[materia] [char](100) NULL,
	[etapa_procesal] [char](50) NULL,
	[ubicacion] [char](50) NULL,
	[especialista_legal] [char](50) NULL,
	[proceso] [char](50) NULL,
	[estado] [char](50) NULL,
	[fecha_conclusion] [date] NULL,
	[motivo_conclusion] [char](50) NULL,
	[sumilla] [varchar](500) NULL,
	[id_secuencia] [int] NOT NULL,
 CONSTRAINT [PK_EXPEDIENTE_DETALLE] PRIMARY KEY CLUSTERED 
(
	[numero_expediente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXPEDIENTE_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_EXPEDIENTE_DETALLE_EXPEDIENTE_CABECERA] FOREIGN KEY([id_secuencia])
REFERENCES [dbo].[EXPEDIENTE_CABECERA] ([id_secuencia])
GO

ALTER TABLE [dbo].[EXPEDIENTE_DETALLE] CHECK CONSTRAINT [FK_EXPEDIENTE_DETALLE_EXPEDIENTE_CABECERA]
GO

CREATE TABLE [dbo].[EXPEDIENTE_PARTES](
	[parte] [char](50) NOT NULL,
	[tipo_persona] [char](50) NOT NULL,
	[nombres] [char](50) NOT NULL,
	[apellido_paterno] [char](50) NOT NULL,
	[apellido_materno] [char](50) NOT NULL,
	[razon_social] [char](100) NULL,
	[numero_expediente] [char](27) NOT NULL,
	[id_parte] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_id_parte] PRIMARY KEY CLUSTERED 
(
	[id_parte] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXPEDIENTE_PARTES]  WITH CHECK ADD  CONSTRAINT [FK_EXPEDIENTE_PARTES_EXPEDIENTE_DETALLE] FOREIGN KEY([numero_expediente])
REFERENCES [dbo].[EXPEDIENTE_DETALLE] ([numero_expediente])
GO

ALTER TABLE [dbo].[EXPEDIENTE_PARTES] CHECK CONSTRAINT [FK_EXPEDIENTE_PARTES_EXPEDIENTE_DETALLE]
GO
CREATE TABLE [dbo].[EXPEDIENTE_SEGUIMIENTO](
	[fecha] [date] NOT NULL,
	[resolucion] [char](10) NOT NULL,
	[tipo_notificacion] [char](50) NULL,
	[sumilla] [char](500) NULL,
	[descripcion_usuario] [char](100) NULL,
	[acto] [char](50) NULL,
	[folio] [int] NULL,
	[proveido] [date] NULL,
	[numero_expediente] [char](27) NOT NULL,
	[id_seguimiento] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_id_seguimiento] PRIMARY KEY CLUSTERED 
(
	[id_seguimiento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXPEDIENTE_SEGUIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_EXPEDIENTE_SEGUIMIENTO_EXPEDIENTE_DETALLE] FOREIGN KEY([numero_expediente])
REFERENCES [dbo].[EXPEDIENTE_DETALLE] ([numero_expediente])
GO

ALTER TABLE [dbo].[EXPEDIENTE_SEGUIMIENTO] CHECK CONSTRAINT [FK_EXPEDIENTE_SEGUIMIENTO_EXPEDIENTE_DETALLE]
GO

CREATE TABLE [dbo].[INSTANCIA](
	[id_instancia] [int] NOT NULL,
	[nombre_instancia] [char](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_instancia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO